name: eshops
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.0.0
  intl: ^0.18.1
  dio: ^5.9.0
  animations: ^2.1.1
  flutter_easyloading: ^3.0.5
  equatable: ^2.0.8
  talker_bloc_logger: ^5.1.10
  flutter_svg: ^2.2.3
  lottie: ^3.3.1
  talker_flutter: ^5.1.10
  sqflite: ^2.4.2
  pinput: ^6.0.1
  step_progress: ^2.7.1
  easy_refresh: ^3.4.0
  connectivity_plus: ^6.1.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/icons/svg/
    - assets/images/icons/png/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
